name : Python CI
on:
  push:
    branches:
      - main
    pull_request:
      branches:
        - main

jobs:
  test:
    runs-on: ubuntu-lastest

    steps:
    ## step 1 : Check out the code from the repo
      - name: Check out code
        uses: actions/checout@v2

    ## step 2 : setup python environment
      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python version: '3.9'
    ## Step 3: Install Dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

    ## Step 4: Run tests
      - name: run tests
        run: pytest 
